name: SELE CI Using Node.js and TypeScript and ESLint and Prettier database MongoDB with Mongoose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    # - name: Type Check (Skip Lib Error)
    #   run: yarn tsc --noEmit --skipLibCheck

    - name: Lint Check
      run: yarn lint:check