name: SELE CI Using Node.js and TypeScript and ESLint and Prettier database MongoDB with Mongoose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Latest stable Node.js version
          cache: 'yarn'       # Yarn dependency caching enabled

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: TypeScript compile check
        run: yarn tsc --noEmit

      - name: Lint check
        run: yarn lint:check